In [9]:
import duckdb
import os

MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")

# 1. Iniciar conexão em memória
con = duckdb.connect()

# 2. Carregar extensões para ler S3 (MinIO)
con.execute("INSTALL httpfs; LOAD httpfs;")

# 3. Configurar acesso ao MinIO (localhost pois você está fora do Docker)
con.execute("SET s3_endpoint='localhost:9000';")
con.execute(f"SET s3_access_key_id={MINIO_ACCESS_KEY};")
con.execute(f"SET s3_secret_access_key={MINIO_SECRET_KEY};") # Use sua senha do .env
con.execute("SET s3_use_ssl=false; SET s3_url_style='path';")

# 4. Ler o arquivo Gold e transformar em DataFrame Pandas
df_produtos = con.execute("SELECT * FROM read_parquet('s3://data-lake/gold/resumo_produtos.parquet')").df()

# 5. Ver o resultado
display(df_produtos)

         categoria  total_de_produtos  preco_medio
0         jewelery                  4       221.00
1  womens_clothing                  6        26.29
2    mens_clothing                  4        51.06
3      electronics                  6       332.50

In [10]:
df_carrinhos = con.execute("SELECT * FROM read_parquet('s3://data-lake/gold/resumo_carrinhos.parquet')").df()
display(df_carrinhos)

   id_usuario  total_carrinhos_abertos  total_itens_comprados
0           1                        2                   27.0
1           3                        2                    6.0
2           4                        1                    5.0
3           2                        1                    3.0
4           8                        1                    1.0

In [11]:
df_users = con.execute("SELECT * FROM read_parquet('s3://data-lake/gold/resumo_usuarios.parquet')").df()
display(df_carrinhos)

   id_usuario  total_carrinhos_abertos  total_itens_comprados
0           1                        2                   27.0
1           3                        2                    6.0
2           4                        1                    5.0
3           2                        1                    3.0
4           8                        1                    1.0